# Generated by Django 5.1.5 on 2025-02-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_orders", "0002_alter_order_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
