# Generated by Django 5.1.5 on 2025-02-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mycustomuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mycustomuser",
            name="verification_code",
            field=models.CharField(blank=True, default="", max_length=6, null=True),
        ),
    ]
