# Generated by Django 5.1.5 on 2025-02-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="promocode",
        ),
    ]
