# Generated by Django 5.1.5 on 2025-02-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("brand", models.CharField(max_length=50)),
                ("price", models.ImageField(blank=True, upload_to="products_images/")),
            ],
        ),
    ]
