# Generated by Django 5.1.5 on 2025-02-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoes",
            name="image",
            field=models.ImageField(blank=True, upload_to="products_images/"),
        ),
        migrations.AlterField(
            model_name="shoes",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
